/*
 * This source file was generated by the Gradle 'init' task
 */
package com.thefifthcontinent.movies;

import java.util.ArrayList;
import java.util.List;

import com.thefifthcontinent.movies.menu.Menu;
import com.thefifthcontinent.movies.menu.Option;
import com.thefifthcontinent.movies.model.Movie;
import com.thefifthcontinent.movies.view.View;

public class App 
{
	private List<Movie> movies = new ArrayList<>();
	private final View view = new View();
	
    public static void main(String[] args) 
    {
    	new App().run();
    }
    
    private void run()
    {
    	Menu menu = createMenu();
    	Option choice = null;
    	
    	do {
			menu.render();
			choice = menu.getChoice();
			
			if (choice != null && choice.getOption() != 'Q') {
				choice.getAction().run();
			}
			
		} while (choice.getOption() != 'Q');
    }
    
    private void addMovie()
    {
    	view.header("Adding Movie");
    	
    	
    }
    
    private Menu createMenu()
    {
    	Menu menu = new Menu("Main Menu");
    	menu.addOption(new Option("Add New Movie", 'A', this::addMovie));
    	menu.addOption(new Option("Edit Movie", 'E', null));
    	menu.addOption(new Option("Delete Movie", 'D', null));
    	menu.addOption(new Option("Search Movies", 'S', null));
    	menu.addOption(new Option("View Movie", 'V', null));
    	menu.addOption(new Option("Quit", 'Q', null));

    	return menu;
    }
}
